services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    volumes:
      - /home/markovivas/dockge/navidrome/music:/music
      - /home/markovivas/dockge/navidrome/data/navidrome:/data
    environment:
      - ND_LOGLEVEL=info
      - ND_SCANINTERVAL=1m
      - ND_SESSIONTIMEOUT=24h
    ports:
      - "4533:4533"
    restart: unless-stopped