services:
  postgres:
    image: postgres:14-alpine
    container_name: planka_postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - /home/markovivas/dockge/planka/data/db-data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5
  planka:
    image: ghcr.io/plankanban/planka:latest
    container_name: planka_app
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 4000:1337
    environment:
      - BASE_URL=${BASE_URL}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${DEFAULT_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME}
    volumes:
      - /home/markovivas/dockge/planka/data/user-avatars:/app/public/user-avatars
      - /home/markovivas/dockge/planka/data/project-background-images:/app/public/project-background-images
      - /home/markovivas/dockge/planka/data/attachments:/app/private/attachments
      - /home/markovivas/dockge/planka/data/planka-data:/opt/planka
volumes:
  user-avatars: null
  project-background-images: null
  attachments: null
  db-data: null
  planka-data: null
networks: {}
