services:
  server:
    image: gitea/gitea:1.21.5
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID=${USER_UID}
      - USER_GID=${USER_GID}
      - GITEA__database__DB_TYPE=${GITEA_DB_TYPE}
      - GITEA__database__HOST=${GITEA_DB_HOST}
      - GITEA__database__NAME=${GITEA_DB_NAME}
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PASSWD}
      - GITEA__server__DOMAIN=${GITEA_DOMAIN}
      - GITEA__server__SSH_PORT=${GITEA_SSH_PORT}
      - GITEA__server__HTTP_PORT=${GITEA_HTTP_PORT}
      - GITEA__server__ROOT_URL=${GITEA_ROOT_URL}
    restart: always
    volumes:
      - /home/markovivas/dockge/gitea/gitea/data:/data
      - /home/markovivas/dockge/gitea/gitea/config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db
    networks:
      - gitea

  db:
    image: mysql:8.0
    container_name: gitea_db
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_CHARSET=${MYSQL_CHARSET}
      - MYSQL_COLLATION=${MYSQL_COLLATION}
    volumes:
      - /home/markovivas/dockge/gitea/gitea/mysql:/var/lib/mysql
    networks:
      - gitea

networks:
  gitea:
    driver: bridge
